name: Build Windows Executable

on:
  workflow_dispatch: # Ermöglicht das manuelle Auslösen des Workflows über die GitHub-Oberfläche

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Passe die Version an, falls du eine andere bevorzugst

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --noconsole --clean --icon="assets
umlock.ico" --add-data "assets;assets" numlock_tray.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NumLockTray-Windows
        path: dist/numlock_tray.exe
